"""add_new_date_column for expenses

Revision ID: c678ff7dc530
Revises: 7c2f4e6b9a31
Create Date: 2026-09-14 18:09:36.739824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c678ff7dc530'
down_revision: Union[str, Sequence[str], None] = '7c2f4e6b9a31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
